import { registerAs } from '@nestjs/config';

export default registerAs('config', () => ({
  port: Number(process.env.PORT) || 3343,
  dbHost: process.env.DB_HOST || 'localhost',
  dbPort: Number(process.env.DB_PORT) || 3306,
  dbUser: process.env.DB_USER || 'root',
  dbPassword: process.env.DB_PASSWORD || '',
  dbName: process.env.DB_NAME || 'govwinhub',
  environment: process.env.NODE_ENV || 'development',
  bodyLimit: process.env.BODY_LIMIT || '100kb',
  tokenExpireTime: process.env.TOKEN_EXPIRY,
  frontendUrl: process.env.FRONTEND,
  accessSecret: process.env.JWT_ACCESS_SECRET,
  refreshSecret: process.env.JWT_REFRESH_SECRET,
  audience: process.env.JWT_TOKEN_AUDIENCE,
  issuer: process.env.JWT_TOKEN_ISSUER,
  accessTokenTtl: parseInt(process.env.JWT_ACCESS_TOKEN_TTL || '3600', 10),
  refreshTokenTtl: parseInt(process.env.JWT_REFRESH_TOKEN_TTL || '86400', 10),
  forgotPasswordRoute: process.env.FORGOT_PASSWORD_ROUTE,
  allowedOrigins: process.env.CORS_ALLOWED_ORIGINS,
  redisHost: process.env.REDISHOST,
  redisPort: parseInt(process.env.REDISPORT || '6379', 10),
  redisPassword: process.env.REDISPASSWORD,
  redisUrl: process.env.REDISURL,
  redisTlsEnabled: process.env.REDIS_TLS_ENABLED,
  elasticsearchNode: process.env.ELASTICSEARCH_NODE || 'http://localhost:9200',
  elasticsearchUsername: process.env.ELASTICSEARCH_USERNAME || '',
  elasticsearchPassword: process.env.ELASTICSEARCH_PASSWORD || '',
}));
