import * as Joi from 'joi';

export default Joi.object({
  NODE_ENV: Joi.string().valid('development', 'production', 'test', 'staging').default('development'),
  PORT: Joi.number().port().default(3000),
  DB_HOST: Joi.string().default('localhost'),
  DB_PORT: Joi.number().default(3306),
  DB_USER: Joi.string().default('root'),
  DB_PASSWORD: Joi.string().allow('').default(''),
  DB_NAME: Joi.string().default('govwinhub'),
  JWT_ACCESS_SECRET: Joi.string().required(),
  JWT_SECRET: Joi.string().required(),
  JWT_REFRESH_SECRET: Joi.string().required(),
  JWT_ACCESS_TOKEN_TTL: Joi.number().default(3600),
  JWT_REFRESH_TOKEN_TTL: Joi.number().default(86400),
  SMTP_HOST: Joi.string().optional(),
  SMTP_PORT: Joi.number().optional(),
  SMTP_SERVICE: Joi.string().optional(),
  SMTP_MAIL: Joi.string().optional(),
  SMTP_PASSWORD: Joi.string().optional(),
  ZOOM_ACCOUNT_ID: Joi.string().optional(),
  ZOOM_CLIENT_ID: Joi.string().optional(),
  ZOOM_CLIENT_SECRET: Joi.string().optional(),
  FRONTEND: Joi.string().optional(),
  FORGOT_PASSWORD_ROUTE: Joi.string().optional(),
  CORS_ALLOWED_ORIGINS: Joi.string().optional(),
  REDISHOST: Joi.string().optional(),
  REDISURL: Joi.string().optional(),
  REDISPASSWORD: Joi.string().allow('').optional(),
  REDISPORT: Joi.number().optional(),
  REDIS_TLS_ENABLED: Joi.string().optional(),
  ELASTICSEARCH_NODE: Joi.string().default('http://localhost:9200'),
  ELASTICSEARCH_USERNAME: Joi.string().allow('').default(''),
  ELASTICSEARCH_PASSWORD: Joi.string().allow('').default(''),
});
